spring:
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://h2db:1521/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none