version: "3.10"

services:
  querydsl-example-db:
    container_name: querydsl-example-db
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=querydsl-example
      - POSTGRES_PASSWORD=querydsl-example
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data